demo/config/routes.rb
Demo::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end

end

demo/app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

demo/app/models/line_item.rb
class LineItem < ActiveRecord::Base
	attr_accessible :product, :cart, :product_id, :cart_id, :quantity
	belongs_to :order
	belongs_to :product
	belongs_to :cart

	def total_price
		product.price * quantity
	end
end

demo/app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  has_many :line_items, dependent: :destroy

  def add_line_items_from_cart(cart)
  	cart.line_items.each do |item|
  		item.cart_id = nil
  		line_items << item
  	end
  end
end

demo/app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	has_many :orders, through: :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	#attr_accessible :description, :image_url, :price, :title
	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)$}i,
		message: 'must be a URL for GIF, JPG or PNG image.'
	}

	private
	# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end
	end
end

demo/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_digest, :password, :password_confirmation
  validates :name, presence: true, uniqueness: true
	has_secure_password
	after_destroy :ensure_an_admin_remains

	private
	def ensure_an_admin_remains
		if User.count.zero?
			raise "Can't delete last user"
		end
	end
end

demo/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@total_orders = Order.count
  end
end

demo/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    # @cart = Cart.find(params[:id])
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end
end

demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end

  def goodbye
  end
end

demo/app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_filter :authorize

  def index
  	if params[:set_locale]
		redirect_to store_path(locale: params[:set_locale])
	else
		@products = Product.order(:title)
		@cart = current_cart
	end
  end
end

demo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted"
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

demo/app/helpers/admin_helper.rb
module AdminHelper
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
	def hidden_div_if(condition, attributes = {}, &block)
		if condition
			attributes["style"] = "display: none"
		end
		content_tag("div", attributes, &block)
	end
end

demo/app/helpers/carts_helper.rb
module CartsHelper
end

demo/app/helpers/line_items_helper.rb
module LineItemsHelper
end

demo/app/helpers/orders_helper.rb
module OrdersHelper
end

demo/app/helpers/products_helper.rb
module ProductsHelper
end

demo/app/helpers/say_helper.rb
module SayHelper
end

demo/app/helpers/sessions_helper.rb
module SessionsHelper
end

demo/app/helpers/store_helper.rb
module StoreHelper
end

demo/app/helpers/users_helper.rb
module UsersHelper
end

demo/app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Pragprog Books Online Store</title>
	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>
</head>
<body class="<%= controller.controller_name %>">
	<div id="banner">
		<%= form_tag store_path, class: 'locale' do %>
			<%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
			<%= submit_tag 'submit' %>
			<%= javascript_tag "$('.locale input').hide()" %>
		<% end %>
		<%= image_tag("logo.png") %>
		<%= @page_title || t('.title') %>
	</div>
	<div id="columns">
		<div id="side">
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
					<%= render @cart %>
				<% end %>
			<% end %>
			
			<ul>
				<li><a href="http://www...."><%= t('.home') %></a></li>
				<li><a href="http://www..../faq"><%= t('.questions') %></a></li>
				<li><a href="http://www..../news"><%= t('.news') %></a></li>
				<li><a href="http://www..../contact"><%= t('.contact') %></a></li>
			</ul>

			<% if session[:user_id] %>
			<ul>
				<li><%= link_to 'Orders', orders_path %></li>
				<li><%= link_to 'Products', products_path %></li>
				<li><%= link_to 'Users', users_path %></li>
			</ul>
			<%= button_to 'Logout', logout_path, method: :delete %>
			<% end %>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>

demo/app/views/order_notifier/received.text.erb
Dear <%= @order.name %>

Thank you for your recent order from The Pragmatic Store.

You ordered the following items:

<%= render @order.line_items %>

We'll send you a separate e-mail when your order ships.

demo/app/views/order_notifier/shipped.html.erb
<h3>Pragmatic Order Shipped</h3>

<p>
This is just to let you know that we've shipped your recent order:
</p>

<table>
<tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items %>
</table>

demo/app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/app/views/order_notifier/shipped.text.erb